
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - type: bind
        source: ./ha-config/
        target: /config/
    restart: unless-stopped
    privileged: true
    ports:
      - target: 8123
        published: 8123
        protocol: tcp
        mode: host


  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./mosquitto/config/
        target: /mosquitto/config/
      - type: bind
        source: ./mosquitto/log/
        target: /mosquitto/log/
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host

volumes:
  data:
    name: "mqtt-broker-data"
